# Generated by Django 4.1.1 on 2022-09-19 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='InvestorUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Тип счета')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='slug')),
            ],
        ),
        migrations.CreateModel(
            name='SecurityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Тип ценной бумаги',
                'verbose_name_plural': 'Типы ценных бумаг',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Securities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Изображение')),
                ('ticker', models.SlugField(unique=True, verbose_name='Тикер')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='currency', to='account.currency', verbose_name='Валюта')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='securitytype', to='account.securitytype', verbose_name='Тип ценной бумаги')),
            ],
            options={
                'verbose_name': 'Ценная бумага',
                'verbose_name_plural': 'Ценные бумаги',
                'ordering': ['ticker'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='slug')),
                ('quantity', models.DecimalField(decimal_places=0, max_digits=9, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена за штуку')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investor', to='account.investoruser', verbose_name='Инвестор')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='security', to='account.securities', verbose_name='Ценная бумага')),
            ],
        ),
    ]
